/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.uwh;
@org.apache.avro.specific.AvroGenerated
public enum CommandType implements org.apache.avro.generic.GenericEnumSymbol<CommandType> {
  TICK, QUERY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CommandType\",\"namespace\":\"org.uwh\",\"symbols\":[\"TICK\",\"QUERY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
