/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.uwh;
@org.apache.avro.specific.AvroGenerated
public enum RiskFactorType implements org.apache.avro.generic.GenericEnumSymbol<RiskFactorType> {
  Issuer  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RiskFactorType\",\"namespace\":\"org.uwh\",\"symbols\":[\"Issuer\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
