/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.uwh;
@org.apache.avro.specific.AvroGenerated
public enum RiskMeasure implements org.apache.avro.generic.GenericEnumSymbol<RiskMeasure> {
  CR01, JTD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RiskMeasure\",\"namespace\":\"org.uwh\",\"symbols\":[\"CR01\",\"JTD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
