/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.uwh;
@org.apache.avro.specific.AvroGenerated
public enum UIDType implements org.apache.avro.generic.GenericEnumSymbol<UIDType> {
  UIPID, UITID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UIDType\",\"namespace\":\"org.uwh\",\"symbols\":[\"UIPID\",\"UITID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
