/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.uwh;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Utilization extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1035188422022376172L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Utilization\",\"namespace\":\"org.uwh\",\"fields\":[{\"name\":\"Threshold\",\"type\":\"double\"},{\"name\":\"Exposure\",\"type\":\"double\"},{\"name\":\"Utilization\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Utilization> ENCODER =
      new BinaryMessageEncoder<Utilization>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Utilization> DECODER =
      new BinaryMessageDecoder<Utilization>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Utilization> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Utilization> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Utilization> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Utilization>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Utilization to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Utilization from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Utilization instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Utilization fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private double Threshold;
   private double Exposure;
   private double Utilization;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Utilization() {}

  /**
   * All-args constructor.
   * @param Threshold The new value for Threshold
   * @param Exposure The new value for Exposure
   * @param Utilization The new value for Utilization
   */
  public Utilization(java.lang.Double Threshold, java.lang.Double Exposure, java.lang.Double Utilization) {
    this.Threshold = Threshold;
    this.Exposure = Exposure;
    this.Utilization = Utilization;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Threshold;
    case 1: return Exposure;
    case 2: return Utilization;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Threshold = (java.lang.Double)value$; break;
    case 1: Exposure = (java.lang.Double)value$; break;
    case 2: Utilization = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Threshold' field.
   * @return The value of the 'Threshold' field.
   */
  public double getThreshold() {
    return Threshold;
  }


  /**
   * Sets the value of the 'Threshold' field.
   * @param value the value to set.
   */
  public void setThreshold(double value) {
    this.Threshold = value;
  }

  /**
   * Gets the value of the 'Exposure' field.
   * @return The value of the 'Exposure' field.
   */
  public double getExposure() {
    return Exposure;
  }


  /**
   * Sets the value of the 'Exposure' field.
   * @param value the value to set.
   */
  public void setExposure(double value) {
    this.Exposure = value;
  }

  /**
   * Gets the value of the 'Utilization' field.
   * @return The value of the 'Utilization' field.
   */
  public double getUtilization() {
    return Utilization;
  }


  /**
   * Sets the value of the 'Utilization' field.
   * @param value the value to set.
   */
  public void setUtilization(double value) {
    this.Utilization = value;
  }

  /**
   * Creates a new Utilization RecordBuilder.
   * @return A new Utilization RecordBuilder
   */
  public static org.uwh.Utilization.Builder newBuilder() {
    return new org.uwh.Utilization.Builder();
  }

  /**
   * Creates a new Utilization RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Utilization RecordBuilder
   */
  public static org.uwh.Utilization.Builder newBuilder(org.uwh.Utilization.Builder other) {
    if (other == null) {
      return new org.uwh.Utilization.Builder();
    } else {
      return new org.uwh.Utilization.Builder(other);
    }
  }

  /**
   * Creates a new Utilization RecordBuilder by copying an existing Utilization instance.
   * @param other The existing instance to copy.
   * @return A new Utilization RecordBuilder
   */
  public static org.uwh.Utilization.Builder newBuilder(org.uwh.Utilization other) {
    if (other == null) {
      return new org.uwh.Utilization.Builder();
    } else {
      return new org.uwh.Utilization.Builder(other);
    }
  }

  /**
   * RecordBuilder for Utilization instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Utilization>
    implements org.apache.avro.data.RecordBuilder<Utilization> {

    private double Threshold;
    private double Exposure;
    private double Utilization;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.uwh.Utilization.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Threshold)) {
        this.Threshold = data().deepCopy(fields()[0].schema(), other.Threshold);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Exposure)) {
        this.Exposure = data().deepCopy(fields()[1].schema(), other.Exposure);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Utilization)) {
        this.Utilization = data().deepCopy(fields()[2].schema(), other.Utilization);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Utilization instance
     * @param other The existing instance to copy.
     */
    private Builder(org.uwh.Utilization other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.Threshold)) {
        this.Threshold = data().deepCopy(fields()[0].schema(), other.Threshold);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Exposure)) {
        this.Exposure = data().deepCopy(fields()[1].schema(), other.Exposure);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Utilization)) {
        this.Utilization = data().deepCopy(fields()[2].schema(), other.Utilization);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'Threshold' field.
      * @return The value.
      */
    public double getThreshold() {
      return Threshold;
    }


    /**
      * Sets the value of the 'Threshold' field.
      * @param value The value of 'Threshold'.
      * @return This builder.
      */
    public org.uwh.Utilization.Builder setThreshold(double value) {
      validate(fields()[0], value);
      this.Threshold = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Threshold' field has been set.
      * @return True if the 'Threshold' field has been set, false otherwise.
      */
    public boolean hasThreshold() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Threshold' field.
      * @return This builder.
      */
    public org.uwh.Utilization.Builder clearThreshold() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Exposure' field.
      * @return The value.
      */
    public double getExposure() {
      return Exposure;
    }


    /**
      * Sets the value of the 'Exposure' field.
      * @param value The value of 'Exposure'.
      * @return This builder.
      */
    public org.uwh.Utilization.Builder setExposure(double value) {
      validate(fields()[1], value);
      this.Exposure = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Exposure' field has been set.
      * @return True if the 'Exposure' field has been set, false otherwise.
      */
    public boolean hasExposure() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Exposure' field.
      * @return This builder.
      */
    public org.uwh.Utilization.Builder clearExposure() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Utilization' field.
      * @return The value.
      */
    public double getUtilization() {
      return Utilization;
    }


    /**
      * Sets the value of the 'Utilization' field.
      * @param value The value of 'Utilization'.
      * @return This builder.
      */
    public org.uwh.Utilization.Builder setUtilization(double value) {
      validate(fields()[2], value);
      this.Utilization = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Utilization' field has been set.
      * @return True if the 'Utilization' field has been set, false otherwise.
      */
    public boolean hasUtilization() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Utilization' field.
      * @return This builder.
      */
    public org.uwh.Utilization.Builder clearUtilization() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Utilization build() {
      try {
        Utilization record = new Utilization();
        record.Threshold = fieldSetFlags()[0] ? this.Threshold : (java.lang.Double) defaultValue(fields()[0]);
        record.Exposure = fieldSetFlags()[1] ? this.Exposure : (java.lang.Double) defaultValue(fields()[1]);
        record.Utilization = fieldSetFlags()[2] ? this.Utilization : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Utilization>
    WRITER$ = (org.apache.avro.io.DatumWriter<Utilization>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Utilization>
    READER$ = (org.apache.avro.io.DatumReader<Utilization>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.Threshold);

    out.writeDouble(this.Exposure);

    out.writeDouble(this.Utilization);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.Threshold = in.readDouble();

      this.Exposure = in.readDouble();

      this.Utilization = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.Threshold = in.readDouble();
          break;

        case 1:
          this.Exposure = in.readDouble();
          break;

        case 2:
          this.Utilization = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










